name: CI/CD Pipeline to Deploy on EC2

on:
  push:
    branches:
      - deployment-iris-rag-be # Trigger deployment when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up SSH client
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Run deployment commands
    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.68.230.234 << 'EOF'
          cd /home/ubuntu/iris-rag-backend/AUB-RAG-BE
          git pull
          git checkout deployment-iris-rag-be
          sudo docker-compose down
          sudo docker rmi $(docker images -q aub-rag-be-web) || true
          sudo docker-compose up --build -d
          echo "Deployment complete."
        EOF
